name: RealEstate.API CI/CD (Render)

on:
  push:
    branches: ["main"]

jobs:
  backend:
    name: Build & Test (.NET 9)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore
        run: dotnet restore ./RealEstate.API.csproj

      - name: Build
        run: dotnet build ./RealEstate.API.csproj --configuration Release --no-restore

      - name: Test
        run: |
          if [ -f ./RealEstate.Tests/RealEstate.Tests.csproj ]; then
            dotnet test ./RealEstate.Tests/RealEstate.Tests.csproj --configuration Release --no-build --verbosity normal
          else
            echo "No test project, skipping."
          fi

  docker:
    name: Build & Push Docker
    runs-on: ubuntu-latest
    needs: [backend]
    env:
      IMAGE_NAME: jorgelmunozp/realestate-api
      IMAGE_TAG: 1.0.${{ github.run_number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: ./
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_NAME }}:latest

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - name: Call Render deploy hook
        run: |
          curl -X POST "https://api.render.com/deploy/srv-${{ secrets.RENDER_BACKEND_ID }}?key=${{ secrets.RENDER_API_KEY }}&imgURL=docker.io/jorgelmunozp/realestate-api:latest"
